server:
  port: 80

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters: 
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

  security:
    oauth2:
    
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/vortexbirdBank
          
  sleuth:
    reactor:
      instrumentation-type: decorate-on-each

  zipkin:
    base-url: http://localhost:9411

#Register in Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
    register-with-eureka: true
      