--Table Model Diego Gomez Mosquera
-- dgomez@vortexbird.com
-- 11/20/2020

-- Table CUSTOMER

CREATE TABLE CUSTOMER(
 CUST_ID integer NOT NULL,
 NAME Varchar NOT NULL,
 ADDRESS Varchar NOT NULL,
 PHONE Varchar NOT NULL,
 EMAIL Varchar NOT NULL,
 TOKEN Varchar NULL,
 ENABLE Varchar NOT NULL,
 DOTY_ID integer
)
;

-- Create indexes for table CUSTOMER

CREATE INDEX IX_Relationship1 ON CUSTOMER (DOTY_ID)
;

-- Add keys for table CUSTOMER

ALTER TABLE CUSTOMER ADD CONSTRAINT Key1 PRIMARY KEY (CUST_ID)
;

-- Table DOCUMENT_TYPE

CREATE TABLE DOCUMENT_TYPE(
 DOTY_ID Serial NOT NULL,
 NAME Varchar NOT NULL,
 ENABLE Varchar NOT NULL
)
;

-- Add keys for table DOCUMENT_TYPE

ALTER TABLE DOCUMENT_TYPE ADD CONSTRAINT Key2 PRIMARY KEY (DOTY_ID)
;

-- Table ACCOUNT

CREATE TABLE ACCOUNT(
 ACCO_ID Varchar NOT NULL,
 BALANCE Numeric(30,6) NOT NULL,
 PASSWORD Varchar NOT NULL,
 ENABLE Varchar NOT NULL,
 VERSION bigint DEFAULT 1 NOT NULL,
 CUST_ID integer
)
;

-- Create indexes for table ACCOUNT

CREATE INDEX IX_Relationship2 ON ACCOUNT (CUST_ID)
;

-- Add keys for table ACCOUNT

ALTER TABLE ACCOUNT ADD CONSTRAINT Key3 PRIMARY KEY (ACCO_ID)
;

-- Table REGISTERED_ACCOUNT

CREATE TABLE REGISTERED_ACCOUNT(
 REAC_ID  Serial NOT NULL,
 CUST_ID integer,
 ACCO_ID Varchar,
 ENABLE Varchar NOT NULL
)
;

-- Create indexes for table REGISTERED_ACCOUNT

CREATE INDEX IX_Relationship3 ON REGISTERED_ACCOUNT (CUST_ID)
;

CREATE INDEX IX_Relationship4 ON REGISTERED_ACCOUNT (ACCO_ID)
;

-- Add keys for table REGISTERED_ACCOUNT

ALTER TABLE REGISTERED_ACCOUNT ADD CONSTRAINT Key4 PRIMARY KEY (REAC_ID )
;

-- Table TRANSACTION

CREATE TABLE TRANSACTION(
 TRAN_ID Serial NOT NULL,
 ACCO_ID Varchar,
 AMOUNT Numeric(30,6) NOT NULL,
 DATE Timestamp NOT NULL,
 USER_EMAIL Varchar,
 TRTY_ID integer
)
;

-- Create indexes for table TRANSACTION

CREATE INDEX IX_Relationship5 ON TRANSACTION (ACCO_ID)
;

CREATE INDEX IX_Relationship7 ON TRANSACTION (USER_EMAIL)
;

CREATE INDEX IX_Relationship8 ON TRANSACTION (TRTY_ID)
;

-- Add keys for table TRANSACTION

ALTER TABLE TRANSACTION ADD CONSTRAINT Key5 PRIMARY KEY (TRAN_ID)
;

-- Table USERS

CREATE TABLE USERS(
 USER_EMAIL Varchar NOT NULL,
 NAME Varchar NOT NULL,
 TOKEN Varchar NULL,
 ENABLE Varchar NOT NULL,
 USTY_ID integer
)
;

-- Create indexes for table USERS

CREATE INDEX IX_Relationship6 ON USERS (USTY_ID)
;

-- Add keys for table USERS

ALTER TABLE USERS ADD CONSTRAINT Key6 PRIMARY KEY (USER_EMAIL)
;

-- Table USER_TYPE

CREATE TABLE USER_TYPE(
 USTY_ID Serial NOT NULL,
 NAME Varchar NOT NULL,
 ENABLE Varchar NOT NULL
)
;

-- Add keys for table USER_TYPE

ALTER TABLE USER_TYPE ADD CONSTRAINT Key7 PRIMARY KEY (USTY_ID)
;

-- Table TRANSACTION_TYPE

CREATE TABLE TRANSACTION_TYPE(
 TRTY_ID Serial NOT NULL,
 NAME Varchar NOT NULL,
 ENABLE Varchar NOT NULL
)
;

-- Add keys for table TRANSACTION_TYPE

ALTER TABLE TRANSACTION_TYPE ADD CONSTRAINT Key8 PRIMARY KEY (TRTY_ID)
;

-- Create relationships section -------------------------------------------------

ALTER TABLE CUSTOMER ADD CONSTRAINT FK_TIPODOCUMENTO_CUSTOMER FOREIGN KEY (DOTY_ID) REFERENCES DOCUMENT_TYPE (DOTY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE ACCOUNT ADD CONSTRAINT FK_CUSTOMER_ACCOUNT FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE REGISTERED_ACCOUNT ADD CONSTRAINT FK_CUSTOMER_REGISTERED_ACCOUNT FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE REGISTERED_ACCOUNT ADD CONSTRAINT FK_ACCOUNT_REGISTERED_ACCOUNT FOREIGN KEY (ACCO_ID) REFERENCES ACCOUNT (ACCO_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE TRANSACTION ADD CONSTRAINT FK_ACCOUNT_TRANSACTION FOREIGN KEY (ACCO_ID) REFERENCES ACCOUNT (ACCO_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE USERS ADD CONSTRAINT FK_USER_TYPE_USERS FOREIGN KEY (USTY_ID) REFERENCES USER_TYPE (USTY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE TRANSACTION ADD CONSTRAINT FK_USERS_TRANSACTION FOREIGN KEY (USER_EMAIL) REFERENCES USERS (USER_EMAIL) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE TRANSACTION ADD CONSTRAINT FK_TRANSACTION_TYPE_TRANSACTION FOREIGN KEY (TRTY_ID) REFERENCES TRANSACTION_TYPE (TRTY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;
